---

- name: Crear carpeta temporal
  ansible.builtin.file:
    path: "{{ path }}"
    mode: '0755'
    state: directory
    

- name: Descargar script instalación
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: "{{ path }}/k3s_script.sh"
    mode: '0644'


- name: Instalar container-selinux
  ansible.builtin.yum:
    name: container-selinux
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"


- name: Ejecutar script
  ansible.builtin.command:
    chdir: "{{ path }}"
    cmd: sh k3s_script.sh
  changed_when: false
    

- name: Eliminar carpeta
  ansible.builtin.file:
    path: "{{ path }}"
    state: absent    


- name: Cambiar permisos a fichero /etc/rancher/k3s/k3s.yaml
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'


- name: Copiar binario kubectl a /usr/bin
  ansible.builtin.copy:
    src: /usr/local/bin/kubectl
    dest: /usr/bin/kubectl
    mode: '0644'
    remote_src: true


- name: Comprobar si kubectl está instalado
  ansible.builtin.command:
    cmd: kubectl version --output=yaml
  register: kubectl
  changed_when: false
  become: false

- name: Msg kubectl instalado
  ansible.builtin.debug:
    msg: "Kubectl instalado. Versión: {{ kubectl.stdout_lines[5][14::]}} "


- name: Leer token
  ansible.builtin.slurp:
    path: /var/lib/rancher/k3s/server/node-token
  register: token_fichero


- name: Guardar token en variable
  ansible.builtin.set_fact:
    token: "{{ token_fichero.content | b64decode }}"


- name: Permitir trafico para k3s
  ansible.posix.firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled
    immediate: true
    

- name: Levantar servicio k3s
  ansible.builtin.service:
    name: k3s
    state: started
    enabled: true

...