---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: master
    image: registry.access.redhat.com/ubi8/ubi-init:8.8-8
    networks:
      - name: "k3s"    
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
  - name: worker-1
    image: registry.access.redhat.com/ubi9/ubi-init:9.2-5
    networks:
      - name: "k3s"    
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
    command: "/usr/sbin/init"
    pre_build_image: true 
provisioner:
  name: ansible
  inventory:
    links:
      hosts: inventory  
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .

...